apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64513
  logSeverityScreen: Info
  # nodeToNodeMeshEnabled: false
  nodeToNodeMeshEnabled: true
  serviceLoadBalancerIPs:
    - cidr: 192.168.11.100/30
  serviceClusterIPs:
    - cidr: 10.96.0.0/16
