#
# delete before applying kubectl delete validatingwebhookconfiguration metallb-webhook-configuration

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    # - 9.11.0.100/32
    - 192.168.10.100/32
    # - 192.168.12.106/32
    # - 192.168.10.100/30
  autoAssign: true
  avoidBuggyIPs: false
#---
#apiVersion: metallb.io/v1beta1
#kind: BGPAdvertisement
#metadata:
#  name: bgp-advert
#  namespace: metallb-system
#spec:
#  ipAddressPools:
#    - ipaddresspool

#---
#apiVersion: metallb.io/v1beta1
#kind: L2Advertisement
#metadata:
#  name: ipadvert
#  namespace: metallb-system
#spec:
#  ipAddressPools:
#    - ipaddresspool
