apiVersion: projectcalico.org/v3
kind: Node
metadata:
  name: 4188479-cg67573
spec:
  bgp:
    asNumber: 64513
    ipv4Address: 192.168.0.6/24

---
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  name: worker1
spec:
  bgp:
    asNumber: 64513
    ipv4Address: 192.168.0.7/24

---
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  name: worker2
spec:
  bgp:
    asNumber: 64513
    ipv4Address: 192.168.0.12/24