apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64512
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  serviceLoadBalancerIPs:
    - cidr: 192.168.100.0/24
  serviceClusterIPs:
    - cidr: 10.96.0.0/16