apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 64512
  logSeverityScreen: Info
  serviceLoadBalancerIps:
    - cidr: 192.168.0.100-192.168.0.120

#  nodeToNodeMeshEnabled: true
