apiVersion: metallb.io/v1beta1
kind: BGPConfiguration
metadata:
  name: default
  namespace: metallb-system
spec:
  logLevel: info
  peers:
    - peerAddress: 192.168.0.13
      peerASN: 64512
      myASN: 64513