#apiVersion: metallb.io/v1beta1
#kind: IPAddressPool
#metadata:
#  name: lb-pool
#  namespace: metallb-system
#spec:
#  addresses:
#    - 192.168.100.0/24
#---
#apiVersion: metallb.io/v1beta1
#kind: BGPAdvertisement
#metadata:
#  name: lb-advertisement
#  namespace: metallb-system
#spec:
#  ipAddressPools:
#    - ipaddresspool
#  communities:
#    - 64513:100