apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    apiVersion: metallb.io/v1beta1
    kind: Config
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250
    bgp:
      asn: 64513 
      peers:
      - peer-address: 192.168.0.13
        peer-asn: 64513
