#
# delete before applying kubectl delete validatingwebhookconfiguration metallb-webhook-configuration

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipaddresspool
  namespace: metallb-system
spec:
  addresses:
  - 213.171.10.112/32
  autoAssign: true
  avoidBuggyIPs: false