---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.10.11

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: 192.168.10.11:6443
apiServer:
  extraArgs:
    advertise-address: 192.168.10.11
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
