---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    resolv-conf: "/run/systemd/resolve/resolv.conf"  # Add the resolv-conf flag here
    node-ip: "192.168.0.6"  # Specify both internal and external IPs

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    advertise-address: "192.168.0.6"
  certSANs:
    - "87.249.54.49"
networking:
  podSubnet: "10.244.0.0/16"
