apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.0.6:6443
    token: "23pgsf.tyiwcy7h0vppgepy"
    caCertHashes:
      - "sha256:4dfeae3e18c1bc396ff7fd47e6b8844952358cae9c3a60af69ba48bd49fdbe78"
nodeRegistration:
  name: worker1
  kubeletExtraArgs:
    node-ip: 192.168.0.7
    hostname-override: worker1
#kubeadm join 192.168.10.11:6443 --token xajpj6.myb4cb6wioonvb2c \
#--discovery-token-ca-cert-hash sha256:d20e222602b161a0cc752129359ab492cdd766e7d8b99b0fb1e23474762be4c9
