---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localALIEndpoint:
  advertise-address: "192.168.0.6"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.0.6

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
#controlPlaneEndpoint: 192.168.0.6:6443
#apiServer:
#  extraArgs:
#    advertise-address: 192.168.0.6
#  certSANs:
#    - "87.249.54.49"
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16

#  podSubnet: "10.244.0.0/16"
