apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: LoadBalancer
  externalIPs:
    - 87.249.54.49
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-service