apiVersion: v1
kind: Service
metadata:
  name: nginx-http
  namespace: default
spec:
  type: LoadBalancer  # Use LoadBalancer to expose externally
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-http